// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUIbjAyBFuaCdOiSFLTlUWMtNNKPcbdzY',
    appId: '1:558176400229:web:f8da51e380d0d6fcace78c',
    messagingSenderId: '558176400229',
    projectId: 'sneh-project-90b29',
    authDomain: 'sneh-project-90b29.firebaseapp.com',
    storageBucket: 'sneh-project-90b29.firebasestorage.app',
    measurementId: 'G-L19KEQ04P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6IRyKSEaDJm1VSgM0qgfkYLufX5s9_oQ',
    appId: '1:558176400229:android:e4ac5a5907292ecface78c',
    messagingSenderId: '558176400229',
    projectId: 'sneh-project-90b29',
    storageBucket: 'sneh-project-90b29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2jKajfmrNhDg496sgIchzY233wZhRNi4',
    appId: '1:558176400229:ios:1333ad5b774f9a9face78c',
    messagingSenderId: '558176400229',
    projectId: 'sneh-project-90b29',
    storageBucket: 'sneh-project-90b29.firebasestorage.app',
    iosBundleId: 'com.example.sneh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2jKajfmrNhDg496sgIchzY233wZhRNi4',
    appId: '1:558176400229:ios:1333ad5b774f9a9face78c',
    messagingSenderId: '558176400229',
    projectId: 'sneh-project-90b29',
    storageBucket: 'sneh-project-90b29.firebasestorage.app',
    iosBundleId: 'com.example.sneh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUIbjAyBFuaCdOiSFLTlUWMtNNKPcbdzY',
    appId: '1:558176400229:web:4ad3d60846fe6437ace78c',
    messagingSenderId: '558176400229',
    projectId: 'sneh-project-90b29',
    authDomain: 'sneh-project-90b29.firebaseapp.com',
    storageBucket: 'sneh-project-90b29.firebasestorage.app',
    measurementId: 'G-3918XH14NH',
  );
}
